### ISSUE TITLE
Caught exception: Couldn't poll for events, error = 4 Error while receiving file changes

### ISSUE THREAD

**Issue by loopedresolve** [finsig/smoldot-kotlin#5]
Gradle displays the following caught exception:

```zsh
Caught exception: Couldn't poll for events, error = 4
Error while receiving file changes
net.rubygrapefruit.platform.NativeException: Couldn't poll for events, error = 4
	at net.rubygrapefruit.platform.internal.jni.AbstractNativeFileEventFunctions$NativeFileWatcher.executeRunLoop0(Native Method)
	at net.rubygrapefruit.platform.internal.jni.AbstractNativeFileEventFunctions$NativeFileWatcher.executeRunLoop(AbstractNativeFileEventFunctions.java:42)
	at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$AbstractFileWatcher$1.run(AbstractFileEventFunctions.java:154)
```

**Comment by loopedresolve** [comment]
This does not impact the build process.  Per the JetBrains issue [KT-36871](https://youtrack.jetbrains.com/issue/KT-36871/Support-Aarch64-Linux-as-a-host-for-the-Kotlin-Native) it appears to be related to running the ubuntu (linux/amd64) Docker container on an Apple Silicon based Mac (linux/arm64/v8).
